package com.coolwallpaper.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tb_user_favourite".
 */
public class LocalFavourite implements java.io.Serializable {

    private Long id;
    private String account;
    private String name;
    private String url;

    public LocalFavourite() {
    }

    public LocalFavourite(Long id) {
        this.id = id;
    }

    public LocalFavourite(Long id, String account, String name, String url) {
        this.id = id;
        this.account = account;
        this.name = name;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
